// Code generated by dbx. DO NOT EDIT.

package model

import (
	"fmt"
	"strings"

	"github.com/pshvedko/dbx/filter"
)

type ObjectList = filter.Injectable[Object]

func (obj Object) Self() filter.Copier {
	return obj
}

func (Object) PK() filter.PK {
	return []string{"id"}
}

func (obj Object) Copy() filter.Projector {
	return &obj
}

func (obj Object) Table() string {
	return ObjectTable
}

var ObjectNames = []string{"id", "uuid_2", "uuid_3", "uuid_4", "bool_1", "bool_2", "bool_3", "bool_4", "float_32", "float_64", "int_8", "int_16", "int_32", "int_64", "string_1", "string_2", "string_3", "string_4", "time_1", "time_2", "time_3", "time_4"}

// Names returns READ ONLY name slice
func (Object) Names() []string {
	return ObjectNames
}

var ObjectColumns = map[string]struct{}{"id": {}, "uuid_2": {}, "uuid_3": {}, "uuid_4": {}, "bool_1": {}, "bool_2": {}, "bool_3": {}, "bool_4": {}, "float_32": {}, "float_64": {}, "int_8": {}, "int_16": {}, "int_32": {}, "int_64": {}, "string_1": {}, "string_2": {}, "string_3": {}, "string_4": {}, "time_1": {}, "time_2": {}, "time_3": {}, "time_4": {}}

// Columns returns READ ONLY name map
func (Object) Columns() map[string]struct{} {
	return ObjectColumns
}

func (obj *Object) Values() []any {
	return []any{&obj.ID, &obj.UUID2, &obj.UUID3, &obj.UUID4, &obj.Bool1, &obj.Bool2, &obj.Bool3, &obj.Bool4, &obj.Float32, &obj.Float64, &obj.Int8, &obj.Int16, &obj.Int32, &obj.Int64, &obj.String1, &obj.String2, &obj.String3, &obj.String4, &obj.Time1, &obj.Time2, &obj.Time3, &obj.Time4}
}

func (obj Object) Value(i int) (any, bool, bool) {
	v, ok := obj.Get(i)
	switch i {
	case 0, 2, 10, 16, 20:
		return v, ok, true
	default:
		return v, ok, false
	}
}

func (obj Object) Get(i int) (any, bool) {
	switch i {
	case 0:
		return filter.NilIfZero(obj.ID)
	case 1:
		return obj.UUID2, false
	case 2:
		return filter.NilIfZero(obj.UUID3)
	case 3:
		return filter.NilIfZero(obj.UUID4)
	case 4:
		return obj.Bool1, false
	case 5:
		return obj.Bool2, false
	case 6:
		return filter.NilIfZero(obj.Bool3)
	case 7:
		return filter.NilIfZero(obj.Bool4)
	case 8:
		return obj.Float32, false
	case 9:
		return filter.NilIfZero(obj.Float64)
	case 10:
		return filter.NilIfZero(obj.Int8)
	case 11:
		return obj.Int16, false
	case 12:
		return filter.NilIfZero(obj.Int32)
	case 13:
		return filter.NilIfZero(obj.Int64)
	case 14:
		return obj.String1, false
	case 15:
		return obj.String2, false
	case 16:
		return filter.NilIfZero(obj.String3)
	case 17:
		return filter.NilIfZero(obj.String4)
	case 18:
		return obj.Time1, false
	case 19:
		return obj.Time2, false
	case 20:
		return filter.NilIfZero(obj.Time3)
	case 21:
		return filter.NilIfZero(obj.Time4)
	default:
		panic(i)
	}
}

func (obj Object) String() string {
	b := &strings.Builder{}
	_, _ = fmt.Fprintf(b, "{id=%v", obj.ID)
	_, _ = fmt.Fprintf(b, " uuid_2=%v", obj.UUID2)
	if obj.UUID3 == nil {
		_, _ = fmt.Fprintf(b, " uuid_3=nil")
	} else {
		_, _ = fmt.Fprintf(b, " uuid_3=%v", *obj.UUID3)
	}
	if obj.UUID4 == nil {
		_, _ = fmt.Fprintf(b, " uuid_4=nil")
	} else {
		_, _ = fmt.Fprintf(b, " uuid_4=%v", *obj.UUID4)
	}
	_, _ = fmt.Fprintf(b, " bool_1=%v", obj.Bool1)
	_, _ = fmt.Fprintf(b, " bool_2=%v", obj.Bool2)
	if obj.Bool3 == nil {
		_, _ = fmt.Fprintf(b, " bool_3=nil")
	} else {
		_, _ = fmt.Fprintf(b, " bool_3=%v", *obj.Bool3)
	}
	if obj.Bool4 == nil {
		_, _ = fmt.Fprintf(b, " bool_4=nil")
	} else {
		_, _ = fmt.Fprintf(b, " bool_4=%v", *obj.Bool4)
	}
	_, _ = fmt.Fprintf(b, " float_32=%v", obj.Float32)
	if obj.Float64 == nil {
		_, _ = fmt.Fprintf(b, " float_64=nil")
	} else {
		_, _ = fmt.Fprintf(b, " float_64=%v", *obj.Float64)
	}
	_, _ = fmt.Fprintf(b, " int_8=%v", obj.Int8)
	_, _ = fmt.Fprintf(b, " int_16=%v", obj.Int16)
	if obj.Int32 == nil {
		_, _ = fmt.Fprintf(b, " int_32=nil")
	} else {
		_, _ = fmt.Fprintf(b, " int_32=%v", *obj.Int32)
	}
	if obj.Int64 == nil {
		_, _ = fmt.Fprintf(b, " int_64=nil")
	} else {
		_, _ = fmt.Fprintf(b, " int_64=%v", *obj.Int64)
	}
	_, _ = fmt.Fprintf(b, " string_1=%v", obj.String1)
	_, _ = fmt.Fprintf(b, " string_2=%v", obj.String2)
	if obj.String3 == nil {
		_, _ = fmt.Fprintf(b, " string_3=nil")
	} else {
		_, _ = fmt.Fprintf(b, " string_3=%v", *obj.String3)
	}
	if obj.String4 == nil {
		_, _ = fmt.Fprintf(b, " string_4=nil")
	} else {
		_, _ = fmt.Fprintf(b, " string_4=%v", *obj.String4)
	}
	_, _ = fmt.Fprintf(b, " time_1=%v", obj.Time1)
	_, _ = fmt.Fprintf(b, " time_2=%v", obj.Time2)
	if obj.Time3 == nil {
		_, _ = fmt.Fprintf(b, " time_3=nil")
	} else {
		_, _ = fmt.Fprintf(b, " time_3=%v", *obj.Time3)
	}
	if obj.Time4 == nil {
		_, _ = fmt.Fprintf(b, " time_4=nil}")
	} else {
		_, _ = fmt.Fprintf(b, " time_4=%v}", *obj.Time4)
	}
	return b.String()
}
