// Code generated by dbx. DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"strings"

	"github.com/pshvedko/dbx"
	"github.com/pshvedko/dbx/filter"
	"github.com/pshvedko/dbx/request"
)

func (Object) Table() string {
	return ObjectTable
}

func (Object) Len() int {
	return 22
}

func (Object) Name() string {
	return "OBJECT"
}

var ObjectPK = []string{"id"}

func (Object) PK() filter.PK {
	return ObjectPK
}

var ObjectNames = []string{"id", "uuid_2", "uuid_3", "uuid_4", "bool_1", "bool_2", "bool_3", "bool_4", "float_32", "float_64", "int_8", "int_16", "int_32", "int_64", "string_1", "string_2", "string_3", "string_4", "time_1", "time_2", "time_3", "time_4"}

func (Object) Names() []string {
	return ObjectNames
}

var ObjectColumns = map[string]int{"id": 0, "uuid_2": 1, "uuid_3": 2, "uuid_4": 3, "bool_1": 4, "bool_2": 5, "bool_3": 6, "bool_4": 7, "float_32": 8, "float_64": 9, "int_8": 10, "int_16": 11, "int_32": 12, "int_64": 13, "string_1": 14, "string_2": 15, "string_3": 16, "string_4": 17, "time_1": 18, "time_2": 19, "time_3": 20, "time_4": 21}

// DEPRECATED: use Index
func (Object) Columns() map[string]int {
	return ObjectColumns
}

func (Object) Exists(key string) bool {
	switch key {
	case "id", "uuid_2", "uuid_3", "uuid_4", "bool_1", "bool_2", "bool_3", "bool_4", "float_32", "float_64", "int_8", "int_16", "int_32", "int_64", "string_1", "string_2", "string_3", "string_4", "time_1", "time_2", "time_3", "time_4":
		return true
	default:
		return false
	}
}

func (obj Object) Copy() filter.Copier {
	return obj
}

func (obj Object) Self() filter.Projector {
	return &obj
}

func (obj *Object) Places() []any {
	return []any{&obj.ID, &obj.UUID2, &obj.UUID3, &obj.UUID4, &obj.Bool1, &obj.Bool2, &obj.Bool3, &obj.Bool4, &obj.Float32, &obj.Float64, &obj.Int8, &obj.Int16, &obj.Int32, &obj.Int64, &obj.String1, &obj.String2, &obj.String3, &obj.String4, &obj.Time1, &obj.Time2, &obj.Time3, &obj.Time4}
}

func (obj Object) Value(i int) (any, bool, bool) {
	v, ok := obj.Field(i)
	switch i {
	case 0, 2, 10, 16, 20:
		return v, ok, true
	default:
		return v, ok, false
	}
}

func (Object) Index(k string) int {
	switch k {
	case "id":
		return 0
	case "uuid_2":
		return 1
	case "uuid_3":
		return 2
	case "uuid_4":
		return 3
	case "bool_1":
		return 4
	case "bool_2":
		return 5
	case "bool_3":
		return 6
	case "bool_4":
		return 7
	case "float_32":
		return 8
	case "float_64":
		return 9
	case "int_8":
		return 10
	case "int_16":
		return 11
	case "int_32":
		return 12
	case "int_64":
		return 13
	case "string_1":
		return 14
	case "string_2":
		return 15
	case "string_3":
		return 16
	case "string_4":
		return 17
	case "time_1":
		return 18
	case "time_2":
		return 19
	case "time_3":
		return 20
	case "time_4":
		return 21
	default:
		panic(k)
	}
}

func (obj Object) Field(i int) (any, bool) {
	switch i {
	case 0:
		return UUIDNilIfZero(obj.ID)
	case 1:
		return obj.UUID2, false
	case 2:
		return UUIDNilIfZero(obj.UUID3)
	case 3:
		return UUIDNilIfZero(obj.UUID4)
	case 4:
		return obj.Bool1, false
	case 5:
		return obj.Bool2, false
	case 6:
		return BoolNilIfZero(obj.Bool3)
	case 7:
		return BoolNilIfZero(obj.Bool4)
	case 8:
		return obj.Float32, false
	case 9:
		return Float64NilIfZero(obj.Float64)
	case 10:
		return BitsNilIfZero(obj.Int8)
	case 11:
		return obj.Int16, false
	case 12:
		return Int32NilIfZero(obj.Int32)
	case 13:
		return Int64NilIfZero(obj.Int64)
	case 14:
		return obj.String1, false
	case 15:
		return obj.String2, false
	case 16:
		return StringNilIfZero(obj.String3)
	case 17:
		return StringNilIfZero(obj.String4)
	case 18:
		return obj.Time1, false
	case 19:
		return obj.Time2, false
	case 20:
		return TimeNilIfZero(obj.Time3)
	case 21:
		return TimeNilIfZero(obj.Time4)
	default:
		panic(i)
	}
}

func (obj Object) String() string {
	b := &strings.Builder{}
	_, _ = fmt.Fprintf(b, "{id=%v", obj.ID)
	_, _ = fmt.Fprintf(b, " uuid_2=%v", obj.UUID2)
	if obj.UUID3 == nil {
		_, _ = fmt.Fprintf(b, " uuid_3=nil")
	} else {
		_, _ = fmt.Fprintf(b, " uuid_3=%v", *obj.UUID3)
	}
	if obj.UUID4 == nil {
		_, _ = fmt.Fprintf(b, " uuid_4=nil")
	} else {
		_, _ = fmt.Fprintf(b, " uuid_4=%v", *obj.UUID4)
	}
	_, _ = fmt.Fprintf(b, " bool_1=%v", obj.Bool1)
	_, _ = fmt.Fprintf(b, " bool_2=%v", obj.Bool2)
	if obj.Bool3 == nil {
		_, _ = fmt.Fprintf(b, " bool_3=nil")
	} else {
		_, _ = fmt.Fprintf(b, " bool_3=%v", *obj.Bool3)
	}
	if obj.Bool4 == nil {
		_, _ = fmt.Fprintf(b, " bool_4=nil")
	} else {
		_, _ = fmt.Fprintf(b, " bool_4=%v", *obj.Bool4)
	}
	_, _ = fmt.Fprintf(b, " float_32=%v", obj.Float32)
	if obj.Float64 == nil {
		_, _ = fmt.Fprintf(b, " float_64=nil")
	} else {
		_, _ = fmt.Fprintf(b, " float_64=%v", *obj.Float64)
	}
	_, _ = fmt.Fprintf(b, " int_8=%v", obj.Int8)
	_, _ = fmt.Fprintf(b, " int_16=%v", obj.Int16)
	if obj.Int32 == nil {
		_, _ = fmt.Fprintf(b, " int_32=nil")
	} else {
		_, _ = fmt.Fprintf(b, " int_32=%v", *obj.Int32)
	}
	if obj.Int64 == nil {
		_, _ = fmt.Fprintf(b, " int_64=nil")
	} else {
		_, _ = fmt.Fprintf(b, " int_64=%v", *obj.Int64)
	}
	_, _ = fmt.Fprintf(b, " string_1=%v", obj.String1)
	_, _ = fmt.Fprintf(b, " string_2=%v", obj.String2)
	if obj.String3 == nil {
		_, _ = fmt.Fprintf(b, " string_3=nil")
	} else {
		_, _ = fmt.Fprintf(b, " string_3=%v", *obj.String3)
	}
	if obj.String4 == nil {
		_, _ = fmt.Fprintf(b, " string_4=nil")
	} else {
		_, _ = fmt.Fprintf(b, " string_4=%v", *obj.String4)
	}
	_, _ = fmt.Fprintf(b, " time_1=%v", obj.Time1)
	_, _ = fmt.Fprintf(b, " time_2=%v", obj.Time2)
	if obj.Time3 == nil {
		_, _ = fmt.Fprintf(b, " time_3=nil")
	} else {
		_, _ = fmt.Fprintf(b, " time_3=%v", *obj.Time3)
	}
	if obj.Time4 == nil {
		_, _ = fmt.Fprintf(b, " time_4=nil}")
	} else {
		_, _ = fmt.Fprintf(b, " time_4=%v}", *obj.Time4)
	}
	return b.String()
}

type ObjectList = dbx.FlatArray[Object]

func (obj *Object) Get(ctx context.Context, db dbx.DBX, options ...request.Option) error {
	return dbx.Get(ctx, db, obj, filter.Eq{"id": obj.ID}, options...)
}

func (obj *Object) Put(ctx context.Context, db dbx.DBX, options ...request.Option) error {
	return dbx.Put(ctx, db, obj, options...)
}

func (obj *Object) Delete(ctx context.Context, db dbx.DBX, options ...request.Option) error {
	return dbx.Delete1(ctx, db, obj, filter.Eq{"id": obj.ID}, options...)
}

func GetObject(ctx context.Context, db dbx.DBX, pk0 ObjectPK0, options ...request.Option) (*Object, error) {
	obj := Object{ID: pk0}
	err := obj.Get(ctx, db, options...)
	if err != nil {
		return nil, err
	}
	return &obj, nil
}

func ListObject(ctx context.Context, db dbx.DBX, f filter.Filter, offset *uint, limit *uint, order []any, options ...request.Option) (uint, []Object, error) {
	var arr ObjectList
	total, err := dbx.List(ctx, db, &arr, f, offset, limit, order, options...)
	if err != nil {
		return 0, nil, err
	}
	return total, arr, nil
}
