// Code generated by dbx. DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"strings"

	"github.com/pshvedko/dbx"
	"github.com/pshvedko/dbx/filter"
	"github.com/pshvedko/dbx/request"
)

func (User) Table() string {
	return UserTable
}

func (User) Len() int {
	return 8
}

func (User) Name() string {
	return "USER"
}

var UserPK = []string{"id"}

func (User) PK() filter.PK {
	return UserPK
}

var UserNames = []string{"id", "domain_id", "login", "active", "user_roles", "created", "updated", "deleted"}

func (User) Names() []string {
	return UserNames
}

var UserColumns = map[string]int{"id": 0, "domain_id": 1, "login": 2, "active": 3, "user_roles": 4, "created": 5, "updated": 6, "deleted": 7}

func (User) Columns() map[string]int {
	return UserColumns
}

func (User) Exists(key string) bool {
	switch key {
	case "id", "domain_id", "login", "active", "user_roles", "created", "updated", "deleted":
		return true
	default:
		return false
	}
}

func (obj User) Copy() filter.Copier {
	return obj
}

func (obj User) Self() filter.Projector {
	return &obj
}

func (obj *User) Places() []any {
	return []any{&obj.ID, &obj.DomainID, &obj.Login, &obj.Active, &obj.UserRoles, &obj.Created, &obj.Updated, &obj.Deleted}
}

func (obj User) Value(i int) (any, bool, bool) {
	v, ok := obj.Field(i)
	switch i {
	case 0, 3:
		return v, ok, true
	default:
		return v, ok, false
	}
}

func (obj User) Field(i int) (any, bool) {
	switch i {
	case 0:
		return UUIDNilIfZero(obj.ID)
	case 1:
		return obj.DomainID, false
	case 2:
		return obj.Login, false
	case 3:
		return BoolNilIfZero(obj.Active)
	case 4:
		return UserRoleNilIfZero(obj.UserRoles)
	case 5:
		return obj.Created, false
	case 6:
		return obj.Updated, false
	case 7:
		return TimeNilIfZero(obj.Deleted)
	default:
		panic(i)
	}
}

func (obj User) String() string {
	b := &strings.Builder{}
	_, _ = fmt.Fprintf(b, "{id=%v", obj.ID)
	_, _ = fmt.Fprintf(b, " domain_id=%v", obj.DomainID)
	_, _ = fmt.Fprintf(b, " login=%v", obj.Login)
	if obj.Active == nil {
		_, _ = fmt.Fprintf(b, " active=nil")
	} else {
		_, _ = fmt.Fprintf(b, " active=%v", *obj.Active)
	}
	if obj.UserRoles == nil {
		_, _ = fmt.Fprintf(b, " user_roles=nil")
	} else {
		_, _ = fmt.Fprintf(b, " user_roles=%v", obj.UserRoles)
	}
	_, _ = fmt.Fprintf(b, " created=%v", obj.Created)
	_, _ = fmt.Fprintf(b, " updated=%v", obj.Updated)
	if obj.Deleted == nil {
		_, _ = fmt.Fprintf(b, " deleted=nil}")
	} else {
		_, _ = fmt.Fprintf(b, " deleted=%v}", *obj.Deleted)
	}
	return b.String()
}

type UserList = dbx.FlatArray[User]

func (obj *User) Get(ctx context.Context, db dbx.DBX, options ...request.Option) error {
	return dbx.Get(ctx, db, obj, filter.Eq{"id": obj.ID}, options...)
}

func (obj *User) Put(ctx context.Context, db dbx.DBX, options ...request.Option) error {
	return dbx.Put(ctx, db, obj, options...)
}

func (obj *User) Delete(ctx context.Context, db dbx.DBX, options ...request.Option) error {
	return dbx.Delete1(ctx, db, obj, filter.Eq{"id": obj.ID}, options...)
}

func GetUser(ctx context.Context, db dbx.DBX, pk0 UserPK0, options ...request.Option) (*User, error) {
	obj := User{ID: pk0}
	err := obj.Get(ctx, db, options...)
	if err != nil {
		return nil, err
	}
	return &obj, nil
}

func ListUser(ctx context.Context, db dbx.DBX, f filter.Filter, offset *uint, limit *uint, order []any, options ...request.Option) (uint, []User, error) {
	var arr UserList
	total, err := dbx.List(ctx, db, &arr, f, offset, limit, order, options...)
	if err != nil {
		return 0, nil, err
	}
	return total, arr, nil
}
