// Code generated by dbx. DO NOT EDIT.

package model

import (
	"fmt"
	"strings"

	"github.com/pshvedko/dbx"
	"github.com/pshvedko/dbx/filter"
)

func (obj User) Self() filter.Copier {
	return obj
}

func (User) PK() filter.PK {
	return []string{"id"}
}

func (obj User) Copy() filter.Projector {
	return &obj
}

func (obj User) Table() string {
	return UserTable
}

var UserNames = []string{"id", "domain_id", "login", "active", "user_roles", "created", "updated", "deleted"}

// Names returns READ ONLY name slice
func (User) Names() []string {
	return UserNames
}

var UserColumns = map[string]int{"id": 0, "domain_id": 1, "login": 2, "active": 3, "user_roles": 4, "created": 5, "updated": 6, "deleted": 7}

// Columns returns READ ONLY name map
func (User) Columns() map[string]int {
	return UserColumns
}

func (obj *User) Places() []any {
	return []any{&obj.ID, &obj.DomainID, &obj.Login, &obj.Active, &obj.UserRoles, &obj.Created, &obj.Updated, &obj.Deleted}
}

func (obj User) Value(i int) (any, bool, bool) {
	v, ok := obj.Field(i)
	switch i {
	case 0, 3:
		return v, ok, true
	default:
		return v, ok, false
	}
}

func (obj User) Field(i int) (any, bool) {
	switch i {
	case 0:
		return filter.NilIfZero(obj.ID)
	case 1:
		return obj.DomainID, false
	case 2:
		return obj.Login, false
	case 3:
		return filter.NilIfZero(obj.Active)
	case 4:
		return filter.NilIfZero(obj.UserRoles)
	case 5:
		return obj.Created, false
	case 6:
		return obj.Updated, false
	case 7:
		return filter.NilIfZero(obj.Deleted)
	default:
		panic(i)
	}
}

func (obj User) String() string {
	b := &strings.Builder{}
	_, _ = fmt.Fprintf(b, "{id=%v", obj.ID)
	_, _ = fmt.Fprintf(b, " domain_id=%v", obj.DomainID)
	_, _ = fmt.Fprintf(b, " login=%v", obj.Login)
	if obj.Active == nil {
		_, _ = fmt.Fprintf(b, " active=nil")
	} else {
		_, _ = fmt.Fprintf(b, " active=%v", *obj.Active)
	}
	if obj.UserRoles == nil {
		_, _ = fmt.Fprintf(b, " user_roles=nil")
	} else {
		_, _ = fmt.Fprintf(b, " user_roles=%v", obj.UserRoles)
	}
	_, _ = fmt.Fprintf(b, " created=%v", obj.Created)
	_, _ = fmt.Fprintf(b, " updated=%v", obj.Updated)
	if obj.Deleted == nil {
		_, _ = fmt.Fprintf(b, " deleted=nil}")
	} else {
		_, _ = fmt.Fprintf(b, " deleted=%v}", *obj.Deleted)
	}
	return b.String()
}

type UserList = dbx.FlatArray[Object]
