// Code generated by dbx. DO NOT EDIT.

package model

import (
	"fmt"
	"strings"

	"github.com/pshvedko/dbx/filter"
)

type UserList = filter.Injectable[User]

func (obj User) Self() filter.Copier {
	return obj
}

func (User) PK() filter.PK {
	return []string{"id"} // FIXME
}

func (obj User) Copy() filter.Projector {
	return &obj
}

func (obj User) Table() string {
	return UserTable
}

func (User) Names() []string {
	return []string{
		"id", "domain_id", "login", "active", "user_roles", "created", "updated", "deleted",
	}
}

func (obj *User) Values() []any {
	return []any{
		&obj.ID, &obj.DomainID, &obj.Login, &obj.Active, &obj.UserRoles, &obj.Created, &obj.Updated, &obj.Deleted,
	}
}

func (obj User) Value(i int) (any, bool, bool) {
	v, ok := obj.Get(i)
	switch i {
	case 0, 2, 10, 16, 20: // FIXME
		return v, ok, true
	default:
		return v, ok, false
	}
}

func (obj User) Get(i int) (any, bool) {
	switch i {
	case 0:
		return obj.ID, false
	case 1:
		return obj.DomainID, false
	case 2:
		return obj.Login, false
	case 3:
		return obj.Active, false
	case 4:
		return filter.NilIfZero(obj.UserRoles)
	case 5:
		return obj.Created, false
	case 6:
		return obj.Updated, false
	case 7:
		return filter.NilIfZero(obj.Deleted)
	default:
		panic(i)
	}
}

func (obj User) String() string {
	b := &strings.Builder{}
	_, _ = fmt.Fprintf(b, "{id=%v", obj.ID)
	_, _ = fmt.Fprintf(b, " domain_id=%v", obj.DomainID)
	_, _ = fmt.Fprintf(b, " login=%v", obj.Login)
	_, _ = fmt.Fprintf(b, " active=%v", obj.Active)
	if obj.UserRoles == nil {
		_, _ = fmt.Fprintf(b, " user_roles=nil")
	} else {
		_, _ = fmt.Fprintf(b, " user_roles=%v", obj.UserRoles)
	}
	_, _ = fmt.Fprintf(b, " created=%v", obj.Created)
	_, _ = fmt.Fprintf(b, " updated=%v", obj.Updated)
	if obj.Deleted == nil {
		_, _ = fmt.Fprintf(b, " deleted=nil}")
	} else {
		_, _ = fmt.Fprintf(b, " deleted=%v}", *obj.Deleted)
	}
	return b.String()
}
